const SITE = {
    name:    "Water",
    age:     16,
    discord: "hokpy",
    roblox:  "https://www.roblox.com/users/2878666652/profile",

    bgm:    "assets/music/theme2.mp3",
    volume: 1,

    profilePin: "water2025",
    adminPin:   "water2025",

    stats: [
        { value: "20+",   label: "Commissions" },
        { value: "4 yrs", label: "Experience"  },
        { value: "40%",   label: "Avg Lag Fix"  },
    ],

    skills: [
        {
            name: "Luau Engineering",
            pct: 98,
            desc: "OOP · Modules · Parallel Luau",
            color: "blue",
        },
        {
            name: "Backend Systems",
            pct: 95,
            desc: "DataStores · ProfileService · Networking",
            color: "gold",
        },
        {
            name: "UI / UX Design",
            pct: 90,
            desc: "Figma · Interface Design · User Flow",
            color: "purple",
        },
        {
            name: "Gameplay Systems",
            pct: 92,
            desc: "Quest Engines · Combat · Mechanics",
            color: "blue",
        },
    ],

    funSkills: [
        { name: "Sleep Schedule",      pct: 2,  desc: "caffeine-dependent",        color: "red"   },
        { name: "Touching Grass",      pct: 5,  desc: "rare event, treat gently",  color: "green" },
        { name: "Googling Errors",     pct: 99, desc: "Stack Overflow MVP",        color: "gold"  },
        { name: "Charging Fair Rates", pct: 75, desc: "use the estimator ↓",      color: "blue"  },
    ],

    timeline: [
        {
            title:  "Freelance Systems Engineer",
            period: "2022 – Present",
            desc:   "Built backend systems, gameplay mechanics, and user interfaces for Roblox games ranging from small commissions to full experiences.",
            tags:   ["DataStore", "UI", "Gameplay", "Optimization"],
            accent: true,
        },
        {
            title:  "Junior Developer",
            period: "2021 – 2022",
            desc:   "Started with Lua and learned through practice, mistakes, debugging, and a lot of trial and error.",
            tags:   [],
            accent: false,
        },
        {
            title:  "The Beginning",
            period: "~2020",
            desc:   "Opened Studio for the first time, moved a baseplate around, and thought that counted as development.",
            tags:   [],
            accent: false,
            dim:    true,
        },
    ],

    projects: [
        {
            title:    "Chillin Place",
            category: "FULL GAME",
            desc:     "Complete hangout place with DataStore persistence and polished presentation.",
            tags:     ["Game Design", "DataStore", "UI"],
            link:     "https://www.roblox.com/games/17290214724/Chillin-Place",
            media:    "image",
            src:      "https://tr.rbxcdn.com/180DAY-c69740761a8556385075f48b5b71147a/768/432/Image/Png/noFilter",
            color:    "gold",
        },
        {
            title:    "Escape Lava: Collect Brainrots",
            category: "FULL GAME",
            desc:     "Casual escape game with progression, UI flow, and saved player data.",
            tags:     ["Game Design", "DataStore", "UI"],
            link:     "https://www.roblox.com/games/85862915773488/Escape-Lava-to-collect-brainrots",
            media:    "image",
            src:      "https://tr.rbxcdn.com/180DAY-1f5e4f49f3ff9eddbf732387c8b19cd7/768/432/Image/Webp/noFilter",
            color:    "gold",
        },
        {
            title:    "Operation: Azure Rift",
            category: "FULL GAME",
            desc:     "Story-driven FPS with systems, UI, and narrative structure inspired by Blue Archive.",
            tags:     ["FPS", "Narrative", "UI"],
            link:     "https://www.roblox.com/games/140471518514522/Operation-Azure-Rift",
            media:    "image",
            src:      "https://tr.rbxcdn.com/180DAY-1384a973e73995479b5db690aa51e902/768/432/Image/Png/noFilter",
            color:    "blue",
        },
        {
            title:    "Yan - Chan Simulator",
            category: "FULL GAME",
            desc:     "A Roblox adaptation focused on progression, presentation, and gameplay flow.",
            tags:     ["Story", "Simulator", "UI"],
            link:     "https://www.roblox.com/games/90515983274647/Yan-Chan-Simulator",
            media:    "image",
            src:      "https://tr.rbxcdn.com/180DAY-cae9bb90f7a6e78c66ed1e18af2727e6/768/432/Image/Webp/noFilter",
            color:    "purple",
        },
        {
            title:    "Blind Mode Logic",
            category: "GAMEPLAY",
            desc:     "Vision restriction mechanic with dynamic spawn handling and clean game-state control.",
            tags:     ["Lighting", "Camera"],
            link:     "",
            media:    "youtube",
            src:      "https://youtu.be/k8hV66kJ8cc",
            color:    "blue",
        },
        {
            title:    "Quest Engine",
            category: "RPG SYSTEM",
            desc:     "Branching dialogue system with quest progression and smooth UI transitions.",
            tags:     ["ModuleScript", "UI Tweening"],
            link:     "",
            media:    "youtube",
            src:      "https://www.youtube.com/watch?v=_HTzGpFwIiU",
            color:    "purple",
        },
        {
            title:    "Dialogue System",
            category: "RPG SYSTEM",
            desc:     "Simple FPS dialogue system built for readability, pacing, and clean interaction flow.",
            tags:     ["ModuleScript", "UI Tweening"],
            link:     "",
            media:    "youtube",
            src:      "https://youtu.be/XJgOCA_q4mM",
            color:    "purple",
        },
        {
            title:    "Farm Optimization",
            category: "OPTIMIZATION",
            desc:     "Backend refactor that reduced server lag by 40% and improved overall stability.",
            tags:     ["Optimization", "Memory"],
            link:     "",
            media:    "youtube",
            src:      "https://youtu.be/YyX5ma58v2Q",
            color:    "gray",
        },
        {
            title:    "Door Kicking Engine",
            category: "GAMEPLAY",
            desc:     "Physics-based door interaction system using CFrame and responsive player control.",
            tags:     ["ModuleScript", "CFrame"],
            link:     "",
            media:    "youtube",
            src:      "https://youtu.be/FjZHsIuzUlY",
            color:    "purple",
        },

        // ── UI DESIGN ─────────────────────────────────────────────
        // Add your UI images here. Set src to your file in assets/images/.
        {
            title:    "My First UI Design",
            category: "UI DESIGN",
            desc:     "Figma UI design.",
            tags:     ["Figma", "UI/UX"],
            link:     "",
            media:    "image",
            src:      "assets/images/UI1.png",
            color:    "purple",
        },
        {
            title:    "My Second UI Design",
            category: "UI DESIGN",
            desc:     "Figma UI design.",
            tags:     ["Figma", "UI/UX"],
            link:     "",
            media:    "image",
            src:      "assets/images/UI2.png",
            color:    "purple",
        },
    ],

    pricing: {
        services: [
            { label: "Quick Task", base: 500   },
            { label: "Bug Fix",    base: 2500  },
            { label: "System",     base: 10000 },
            { label: "Full Game",  base: 30000 },
        ],
        currencies: {
            "R$":  { rate: 1,      prefix: false, sym: " R$" },
            "USD": { rate: 0.0035, prefix: true,  sym: "$"   },
            "THB": { rate: 0.12,   prefix: true,  sym: "฿"   },
            "VND": { rate: 90,     prefix: false, sym: "₫"   },
        },
    },

    seedReviews: [
        { id: "s1", name: "Kurokami_Dev", stars: 5, text: "Fixed a DataStore corruption bug in under an hour that had been killing our game for weeks. 10/10 would hire again.", date: "2025-02-14", verified: true },
        { id: "s2", name: "StellarForge", stars: 5, text: "Built our entire quest engine from scratch. Clean code, great communication, delivered ahead of schedule.", date: "2025-03-02", verified: true },
        { id: "s3", name: "NexusRBX", stars: 5, text: "Reduced server lag by 40% on our farm sim. Rewrote the backend the right way. Professional level work.", date: "2025-04-20", verified: true },
    ],

    konami: ["ArrowUp","ArrowUp","ArrowDown","ArrowDown","ArrowLeft","ArrowRight","ArrowLeft","ArrowRight","b","a"],

    sections: [
        { id: "home",      label: "Home"      },
        { id: "about",     label: "Profile"   },
        { id: "skills",    label: "Skills"    },
        { id: "history",   label: "History"   },
        { id: "projects",  label: "Projects"  },
        { id: "estimator", label: "Estimator" },
        { id: "reviews",   label: "Reviews"   },
        { id: "contact",   label: "Contact"   },
    ],
};
